name: CreateBinaries

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Gatsby
        run: npm install -g gatsby-cli

      - name: Install packages
        run: yarn install 

      - name: Build site
        run: node --max-old-space-size=4096 ./node_modules/.bin/gatsby build #--prefix-paths
      
      - name: package
        run: |
          cd public
          find .
          cd -
          mv public docs
          cd docs
          find .
          cd -
          mkdir public
          mv docs public/docs
          cd public
          find .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

