name: Deployment status

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
  push:
    branches:
      - mastermaster # renamed to mastermaster to prevent builds. This is optimized builds using cache. Disabled as no understanding
    paths-ignore: 
      - 'docs/**'
      - '.vscode/**'
      - '.gitub/**'
      - '!.github/workflows/deploy.yml' # re-deploy after changes to deployment workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x

      - name: Store yarn directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check node_modules cache
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Check Gatsby cache
        id: gatsby-cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-${{ hashFiles('gatsby-*.js') }}-${{ hashFiles('package.json') }}

      - name: Install packages
        if: |
          steps.yarn-cache.outputs.cache-hit != 'true' ||
          steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --network-timeout 300000 && yarn clean

      - name: Build site
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

